language: node_js
node_js:
  - "11"

os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

script:
  - npm run build
  - npm run lint
  - npm run dist

deploy:
  provider: releases
  publish: always
  api_key: GH_TOKEN
  file: 
    - release/speedy-unicode*
  skip_cleanup: true
  draft: true
  on:
    branch: master
