language: node_js
node_js:
  - "11"

os:
  - linux
  - osx
  - windows

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

script:
  - npm run build
  - npm run lint
  - npm run dist

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: 
    - release/mac/*
    - release/windows/*
    - release/linux/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
